# yaml-language-server: $schema=https://json.schemastore.org/circleciconfig.json
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: cimg/node:lts
    resource_class: arm.large
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Build website
          command: yarn build
      - run:
          name: Deploy website
          command: yarn wrangler pages publish public --project-name website

workflows:
  ci:
    jobs:
      - build:
          context: cloudflare
